"""Initial migration.

Revision ID: 20393c703bed
Revises: 7e731457b05d
Create Date: 2022-06-24 20:06:03.535376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20393c703bed'
down_revision = '7e731457b05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passworddd', sa.Text(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.TEXT(), nullable=False))
    op.drop_column('users', 'passworddd')
    # ### end Alembic commands ###
