"""Migration

Revision ID: 2a799ccdb14f
Revises: af2068435c31
Create Date: 2022-06-25 08:16:21.273382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a799ccdb14f'
down_revision = 'af2068435c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('checkin_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('attendance', sa.Column('checkout_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('attendance', 'created_at')
    op.drop_column('attendance', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('attendance', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
    op.drop_column('attendance', 'checkout_at')
    op.drop_column('attendance', 'checkin_at')
    # ### end Alembic commands ###
