"""Initial migration.

Revision ID: 40554799f3f5
Revises: ae1d47e726c3
Create Date: 2022-06-24 20:05:30.950451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40554799f3f5'
down_revision = 'ae1d47e726c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passworddd', sa.Text(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.TEXT(), nullable=False))
    op.drop_column('users', 'passworddd')
    # ### end Alembic commands ###
