"""Initial migration.

Revision ID: af2068435c31
Revises: 20393c703bed
Create Date: 2022-06-24 20:06:20.212909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af2068435c31'
down_revision = '20393c703bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.drop_column('users', 'passworddd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passworddd', mysql.TEXT(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
